// Generated by CoffeeScript 1.12.5
(function() {
  var wordlist;

  wordlist = require('./wordlist.json').wordlist;

  module.exports = function(l) {
    var i, words;
    if (l < 1) {
      return '';
    }
    words = (function() {
      var j, ref, results;
      results = [];
      for (i = j = 1, ref = l; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        results.push(wordlist[Math.floor(Math.random() * wordlist.length)]);
      }
      return results;
    })();
    return words.join(' ');
  };

  module.exports.wordlist = wordlist;

}).call(this);
